### ISSUE TITLE
This isn't released yet, correct? 

### ISSUE THREAD

**Issue by Cmhorn** [kometenstaub/obsidian-linked-data-vocabularies#11]
Unable to get this working in the current version of Obsidian (v0.12.16).

I am certainly no expert on manually installing plugins, so perhaps I am doing something wrong. Extracted the zipped folder to vault/.obsidian/plugins

It appears in Community Plugins, but throws: Can't load plugin error

**Comment by kometenstaub** [comment]
Solved in Discord.

For anyone else wondering, you need to download the latest release from here <https://github.com/kometenstaub/obsidian-linked-data-vocabularies/releases> and *not* the zip file one can download after clicking the green `Code` button on the main page, that only downloads the source code but not the built plugin.
