### ISSUE TITLE
Add quotes around items

### ISSUE THREAD

**Issue by lkadre** [kometenstaub/obsidian-linked-data-vocabularies#5]
Add quotes around each item so that commas and brackets (as some results include them) don't break links/the frontmatter in general. 

ex. 
`narrower: ["History--[period subdivision]--Philosophy","Foreign relations--Philosophy","Civilization--Philosophy","Politics and government--[period subdivision]--Philosophy","History--Philosophy","Politics and government--Philosophy"]` 

instead of 

`narrower: [History--[period subdivision]--Philosophy,Foreign relations--Philosophy,Civilization--Philosophy,Politics and government--[period subdivision]--Philosophy,History--Philosophy,Politics and government--Philosophy]`

**Comment by kometenstaub** [comment]
That should work as of 0.0.6
